# Generated by Django 4.1.5 on 2023-03-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_user_question_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='users',
            new_name='user',
        ),
    ]
